pipeline {
    agent any
    parameters {
        choice(name: 'PROJECT', choices: ['dockerized'], description: 'Select project')
        choice(name: 'CLUSTER', choices: ['Deploy to dev', 'Deploy to prod'], description: 'Select cluster')
        string(name: 'BRANCH', description: 'Enter the branch name')
    }
    environment {
        DEV_CLUSTER = 'dev-cluster'
        PROD_CLUSTER = 'prod-cluster'
    }
    stages {
        stage('--- DETERMINE CLUSTER ---') {
            steps {
                script {
                    echo "Cluster chosen: ${params.CLUSTER}."
                    env.TARGET_CLUSTER = params.CLUSTER == 'Deploy to dev' ? DEV_CLUSTER : PROD_CLUSTER
                }
            }
        }

        stage('--- CHECKOUT CODE ---') {
            steps {
                script {
                    echo "Project chosen: ${params.PROJECT}."
                    echo "Branch chosen: ${params.BRANCH}."

                    def repos = [
                        dockerized: "git@github.com:bespalhuk/dockerized.git"
                    ]

                    def repoUrl = repos[params.PROJECT]
                    echo "Repository URL: ${repoUrl}."

                    git branch: params.BRANCH, url: repoUrl, credentialsId: 'github-ssh-key'
                }
            }
        }

        stage('--- BUMP VERSION: major ---') {
            when {
                expression { false }
            }
            steps {
                script {
                    echo "Skipping for now."
                }
            }
        }

        stage('--- BUMP VERSION: minor ---') {
            when {
                expression { params.CLUSTER == 'Deploy to prod' }
            }
            steps {
                script {
                    echo "Getting current version."
                    def properties = 'gradle.properties'
                    def curVersion = sh(script: "grep '^version=' ${properties} | cut -d'=' -f2", returnStdout: true).trim()

                    echo "Tokenizing current version."
                    def versionTokens = curVersion.tokenize('.')
                    def major = versionTokens[0].toInteger()
                    def minor = versionTokens[1].toInteger()
                    def patch = versionTokens[2].toInteger()

                    minor++
                    patch = 0
                    def newVersion = "${major}.${minor}.${patch}"

                    echo "Updating new version."
                    sh "sed -i 's/^version=.*/version=${newVersion}/' ${properties}"
                    sh "git config --global user.email 'jenkins@example.com'"
                    sh "git config --global user.name 'Jenkins'"
                    sh "git add ${properties}"
                    echo "Committing new version."
                    sh "git commit -m 'Bump version from ${curVersion} to ${newVersion}'"
                    echo "Pushing new version to master."
                    sh "git push origin master"
                    sh "git fetch origin && git checkout develop && git merge origin/master"
                    echo "Pushing new version to develop."
                    sh "git push origin develop"

                    env.VERSION = newVersion
                }
            }
        }

        stage('--- BUMP VERSION: patch ---') {
            when {
                expression { params.CLUSTER == 'Deploy to dev' }
            }
            steps {
                script {
                    echo "Getting current version."
                    def properties = 'gradle.properties'
                    def curVersion = sh(script: "grep '^version=' ${properties} | cut -d'=' -f2", returnStdout: true).trim()

                    echo "Tokenizing current version."
                    def versionTokens = curVersion.tokenize('.')
                    def major = versionTokens[0].toInteger()
                    def minor = versionTokens[1].toInteger()
                    def patch = versionTokens[2].toInteger()

                    patch++
                    def newVersion = "${major}.${minor}.${patch}"

                    echo "Updating new version."
                    sh "sed -i 's/^version=.*/version=${newVersion}/' ${properties}"
                    sh "git config --global user.email 'jenkins@example.com'"
                    sh "git config --global user.name 'Jenkins'"
                    sh "git add ${properties}"
                    echo "Committing new version."
                    sh "git commit -m 'Bump version from ${curVersion} to ${newVersion}'"
                    echo "Pushing new version to ${params.BRANCH}."
                    sh "git push origin ${params.BRANCH}"

                    env.VERSION = newVersion
                }
            }
        }

        stage('--- CREATE TAG ---') {
            when {
                expression { params.CLUSTER == 'Deploy to prod' }
            }
            steps {
                script {
                    echo "Creating tag ${env.VERSION}."
                    sh "git tag ${env.VERSION}"
                    sh "git push origin --tags"
                }
            }
        }

        stage('--- BUILD DOCKER IMAGE ---') {
            steps {
                script {
                    echo "Building docker image ${params.PROJECT}:${env.VERSION}."
                    sh "eval \$(minikube docker-env)"
                    sh "docker build -t ${params.PROJECT}:${env.VERSION} ."
                }
            }
        }

        stage('--- DEPLOY TO KUBE ---') {
            steps {
                script {
                    echo "Deploying to cluster: ${env.TARGET_CLUSTER}."
                    echo "Deploying image: ${params.PROJECT}:${env.VERSION}."
                    sh "kubectl config use-context ${env.TARGET_CLUSTER}"
                    sh "kubectl set image deployment/${params.PROJECT} ${params.PROJECT}=${params.PROJECT}:${env.VERSION}"
                    sh "kubectl expose deployment ${params.PROJECT} --type=NodePort --port=8080"
                }
            }
        }
    }
}
